### PR TITLE
docs(fs): Fix scope example in js inline docs

### LINKED ISSUE #2901: [request] Fix conflicting info on fs scopes
### Question you want answered

How do I allow to access a file?

### Where did you look for an answer?

I was reading a page about [File System](https://v2.tauri.app/plugin/file-system/#examples) plugin in the Guides section, where I got to the "Security" section. The section pointed me to [fs javascript reference](https://v2.tauri.app/reference/javascript/fs/#security), where an example of adding allowed scopes looks like this:
```json
{
  "plugins": {
    "fs": {
      "scope": ["$APPDATA/databases/*"]
    }
  }
}
```
Note that there was no indication of which file to add this snippet to.

I unsuccessfully tried inserting this snippet into `tauri.conf.json`, after which I had to google the right way. It turned out that at the very bottom of the File System guide page there is a section about permissions, which did specify which file to tweak and does seem to work.

So, as I understand it, the snippet in the fs reference page is plain wrong

### Page URL

https://v2.tauri.app/plugin/file-system/#examples

### Additional context

_No response_

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

### PR DESCRIPTION
**Pull request by FabianLars**
fixes https://github.com/tauri-apps/tauri-docs/issues/2901

### CODE REVIEW

**Comment by FabianLars** [comment]
wdym?? there's no diff locally :(

File: plugins/fs/guest-js/index.ts [hunk 1]
```diff
@@ -14,16 +14,27 @@
...
- *   "plugins": {
- *     "fs": {
- *       "scope": ["$APPDATA/databases/*"]
- *     }
- *   }
+ *   "permissions": [
+ *    {
+ *     "identifier": "fs:scope",
+ *     "allow": [{ "path": "$APPDATA/databases/*" }]
+ *   }]
```
Comment (amrbashir) [inline plugins/fs/guest-js/index.ts]:
```suggestion
 *   "permissions": [
 *     {
 *       "identifier": "fs:scope",
 *       "allow": [{ "path": "$APPDATA/databases/*" }]
 *     }
 *   ]
```

File: plugins/fs/guest-js/index.ts [hunk 2]
```diff
@@ -14,16 +14,27 @@
...
+ * ```
+ *
+ * Scopes can also be applied to specific `fs` APIs by using the API's identifier instead of `fs:scope`:
+ * ```json
+ * {
+ *   "permissions": [
+ *    {
+ *     "identifier": "fs:allow-exists",
+ *     "allow": [{ "path": "$APPDATA/databases/*" }]
+ *   }]
```
Comment (amrbashir) [inline plugins/fs/guest-js/index.ts]:
```suggestion
 *   "permissions": [
 *     {
 *       "identifier": "fs:allow-exists",
 *       "allow": [{ "path": "$APPDATA/databases/*" }]
 *     }
 *   ]
```

File: plugins/fs/guest-js/index.ts (hunk 1 above)
Comment (FabianLars) [reply plugins/fs/guest-js/index.ts]: ups

**Review by amrbashir — APPROVED** [review]
