### PR TITLE
fix(updater): preserve file extension of updater package (fix: #3283)

### LINKED ISSUE #3283: [bug] wrong file extension in sudo dialog
### Describe the bug

When using a .deb artifact downloaded from GitHub release, and performing an update using the `tauri-updater-plugin` the popup reqeuesting sudo permissiono uses a misleading file extension:

Image

It's not broken, the update itself works, but it says it wants to install a .rpm using `dpkg` which might make some users suspicious.

### Reproduction

_No response_

### Expected behavior

It would be nice if the temporary file would be named package.deb instead of package.rpm in such a case to not confuse users.

### Full `tauri info` output

```text
[⚠] Environment
    - OS: Arch Linux Unknown x86_64 (X64) (Hyprland on wayland)
    ✔ webkit2gtk-4.1: 2.50.4
    ✔ rsvg2: 2.61.3
    ✔ rustc: 1.93.0 (254b59607 2026-01-19) (Arch Linux rust 1:1.93.0-1)
    ✔ cargo: 1.93.0 (083ac5135 2025-12-15) (Arch Linux rust 1:1.93.0-1)
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 25.6.0
    - npm: 11.8.0

[-] Packages
    - tauri 🦀: 2.10.2
    - tauri-build 🦀: 2.5.5
    - wry 🦀: 0.54.2
    - tao 🦀: 0.34.5
    - tauri-cli 🦀: 2.10.0

[-] Plugins
    - tauri-plugin-clipboard-manager 🦀: 2.3.2
    - tauri-plugin-updater 🦀: 2.10.0
    - tauri-plugin-opener 🦀: 2.5.3
    - tauri-plugin-log 🦀: 2.8.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

### Stack trace

```text

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hrzlgnm**
Closes #3283 

Otherwise users may get confused when seing a sudo dialog which suggests a `rpm` package is installed using `dpkg -i`

### CODE REVIEW

File: plugins/updater/src/updater.rs [hunk 1]
```diff
@@ -1078,7 +1084,7 @@ impl Update {
                     .prefix("tauri_rpm_update")
```
Comment (Legend-Master) [inline plugins/updater/src/updater.rs]: Also this path?

**Review by Legend-Master — DISMISSED** [review]
Thanks! Do you mind also adding a change file?

> https://github.com/tauri-apps/plugins-workspace/blob/v2/.changes/readme.md

File: plugins/updater/src/updater.rs (hunk 1 above)
Comment (hrzlgnm) [reply plugins/updater/src/updater.rs]: Thanks for pointing this out, there were more locations where logging was using `deb` unconditionally I've updated those, too with c501d23

**Comment by hrzlgnm** [comment]
> Thanks! Do you mind also adding a change file?
> 
> > https://github.com/tauri-apps/plugins-workspace/blob/v2/.changes/readme.md

Added here: 5193e3a6c49df7436e83161d6d30a53fe3236a96

File: .changes/change-pr-3285.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"updater": patch
+---
+
+fix: preserve file extension of updater package, otherwise users may get confused when presented with a sudo dialog suggests to install a file with the extension `.rpm` using `dpkg - i`
```
Comment (hrzlgnm) [inline .changes/change-pr-3285.md]:
```suggestion
fix: preserve file extension of updater package, otherwise users may get confused when presented with a sudo dialog suggesting to install a file with the extension `.rpm` using `dpkg - i`
```

File: .changes/change-pr-3285.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"updater": patch
+---
+
+fix: preserve file extension of updater package, otherwise users may get confused when presented with a sudo dialog suggesting to install a file with the extension `.rpm` using `dpkg - i`
```
Comment (hrzlgnm) [inline .changes/change-pr-3285.md]:
```suggestion
fix: preserve file extension of updater package, otherwise users may get confused when presented with a sudo dialog suggesting to install a file with the extension `.rpm` using `dpkg -i`
```

File: .changes/change-pr-3285.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"updater": patch
```
Comment (Legend-Master) [inline .changes/change-pr-3285.md:2]:
```suggestion
"updater": patch
"updater-js": patch
```

**Review by Legend-Master — APPROVED** [review]
Thanks!
