### PR TITLE
fix(fs): can't use Windows path

### LINKED ISSUE #1704: [bug][fs][v2] unable to get path from XX
When I want to read a text file such as `C://users/user/temp.json`, `fs.readTextFile` is work.

But it reports the `unable to get path from c://users/user/temp.json` error recently.

+ `tauri-plugin-fs`: v2
+ `@tauri-apps/plugin-fs`: 2.0.0-rc.1

### PR DESCRIPTION
**Pull request by Legend-Master**
Url deserializes Windows drive letter to url scheme which is not what we wanted, since we don't use single letter schemes anyways, we can just assume a single letter scheme url to be a path not a url

Fix #1704

### CODE REVIEW

File: plugins/fs/src/commands.rs [hunk 1]
```diff
@@ -26,10 +26,26 @@ use crate::{scope::Entry, Error, FilePath, FsExt};
...
+{
+    let url = url::Url::deserialize(deserializer)?;
+    let scheme = url.scheme();
+    if scheme.len() != 1 {
+        Ok(url)
+    } else {
+        Err(serde::de::Error::custom(format!(
+            "Single letter scheme \"{scheme}\" is not supported because it conflicts with Windows paths"
+        )))
+    }
```
Comment (amrbashir) [inline plugins/fs/src/commands.rs]: instead of an error here we should fallback to using a `SafePathBuf`, so instead we should implement `Deserialize` for `SafeFilePath` manually, not just one variant.

**Review by amrbashir — CHANGES_REQUESTED** [review]

File: plugins/fs/src/commands.rs [hunk 2]
```diff
@@ -23,13 +23,43 @@ use std::{
...
 
-#[derive(Debug, serde::Deserialize)]
-#[serde(untagged)]
+#[derive(Debug)]
 pub enum SafeFilePath {
     Url(url::Url),
     Path(SafePathBuf),
 }
 
+impl<'de> serde::Deserialize<'de> for SafeFilePath {
```
Comment (amrbashir) [inline plugins/fs/src/commands.rs:33]: I see that we have a duplicated enum definition with and now same deserialize implementation, maybe we can combine this logic into one, by using generics? and still export aliases without a generic:
```rs 
enum FilePathOrUrl<T: FromStr> {
    Url(url::Url),
    Path(T),
}
pub type SafeFilePath = FilePath<SafeFilePath>;
pub type FilePath = FilePath<PathBuf>;
```

**Review by amrbashir — CHANGES_REQUESTED** [review]

File: plugins/fs/src/commands.rs (hunk 2 above)
Comment (Legend-Master) [reply plugins/fs/src/commands.rs:33]: > ```rust
> enum FilePathOrUrl<T: FromStr> {
>     Url(url::Url),
>     Path(T),
> }
> pub type SafeFilePath = FilePath<SafeFilePath>;
> pub type FilePath = FilePath<PathBuf>;
> ```

I'm not sure how that'll work, `SafeFilePath` doesn't implement `FromStr`, and that means we either need to do it in tauri or we need a wrapper

Comment (amrbashir) [reply plugins/fs/src/commands.rs:33]: The best is to implement `FromStr` on in tauri. For now, we can just add a TODO then or merge as is.

**Comment by amrbashir** [comment]
Also I think we should add some tests in this PR, just to ensure we don't regress again

**Review by amrbashir — APPROVED** [review]
