### PR TITLE
fix(updater): download reuse check timeout

### LINKED ISSUE #2372: [bug][updater] Timeout passed to check() is reused for downloadAndInstall()
For quite a while I have been debugging an issue where the updater often failed on one device while there were no issues at all on other devices. I would never have expected that the timeout I pass to `check()` (JS API) would be reused later when downloading the update by calling `downloadAndInstall()`.

~~I don't think there is a reasonable default value for downloading the update because it depends on the app size and connection speed, so I would suggest to remove it. In case of the updater, timeouts IMHO only make sense for the update check and the connection handshakes.~~

Reproduction repo: https://github.com/dgerhardt/tauri2-updater-test/ (downloads but does not start install for security reasons)

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #2372

Fix `timeout` passed to `check` gets re-used by `download` and `downloadAndinstall` 

Also did some other cleanups

### CODE REVIEW

File: plugins/updater/src/updater.rs [hunk 1]
```diff
@@ -478,10 +475,10 @@ impl Updater {
                 version: release.version.to_string(),
                 date: release.pub_date,
                 download_url: release.download_url(&self.json_target)?.to_owned(),
-                body: release.notes.clone(),
                 signature: release.signature(&self.json_target)?.to_owned(),
+                body: release.notes,
                 raw_json: raw_json.unwrap(),
-                timeout: self.timeout,
+                timeout: None,
```
Comment (Legend-Master) [inline plugins/updater/src/updater.rs:481]: This is the actual change 🙃

File: plugins/updater/src/commands.rs [hunk 2]
```diff
@@ -40,6 +40,8 @@ pub(crate) struct Metadata {
 struct DownloadedBytes(pub Vec<u8>);
 impl Resource for DownloadedBytes {}
 
+// TODO: Align this with the result of `updater.check` to Result<Option<Metadata>>
+// and remove `available` instead of handling this in the js side
```
Comment (Legend-Master) [inline plugins/updater/src/commands.rs:44]: I don't know if it's considered breaking if we change this from returning `Result<Metadata>` to `Result<Option<Metadata>>`, if not then I would like to do it before v3

Comment (amrbashir) [reply plugins/updater/src/commands.rs:44]: We can change it, if you want since we now require users to sync their rust and js versions

**Review by amrbashir — APPROVED** [review]

File: plugins/updater/src/commands.rs (hunk 2 above)
Comment (Legend-Master) [reply plugins/updater/src/commands.rs:44]: That's nice, I'll do it later
