### PR TITLE
fix(dialog): fix message dialog return with custom buttons, fixes #711

### LINKED ISSUE #711: [dialog] v2 confirm always returns true
tauri alpha.17, dialog plugin 2.0.0-alpha.4, macOS
```ts
import { confirm } from "@tauri-apps/plugin-dialog";
const confirmed = await confirm("Are you sure?");
console.log(confirmed);
```

Current behaviour:
Press Ok => returns true
Press Cancel => returns **true**

Expected behaviour:
Press Ok => returns true
Press Cancel => returns **false**

### PR DESCRIPTION
**Pull request by pashokitsme**
Fixes #711 (And removes some unnecessary lines)

### CODE REVIEW

File: plugins/dialog/src/desktop.rs [hunk 1]
```diff
@@ -226,5 +208,13 @@ pub fn show_message_dialog<R: Runtime, F: FnOnce(bool) + Send + 'static>(
     dialog: MessageDialogBuilder<R>,
     f: F,
 ) {
+    use rfd::MessageDialogResult as Result;
```
Comment (amrbashir) [inline plugins/dialog/src/desktop.rs]: Don't rename to `Result` as it might be confused with std's `Result`

File: plugins/dialog/src/desktop.rs [hunk 2]
```diff
@@ -226,5 +208,13 @@ pub fn show_message_dialog<R: Runtime, F: FnOnce(bool) + Send + 'static>(
...
+    let f = move |res| {
+        f(match res {
+            Result::Ok | Result::Yes => true,
+            Result::Custom(s) => s == OK,
```
Comment (amrbashir) [inline plugins/dialog/src/desktop.rs]: This will still fail if the they used a custom ok button label, instead, you should match against `dialog.ok_button_label.unwrap_or_else(|| OK.into)`

**Review by amrbashir — CHANGES_REQUESTED** [review]

**Comment by amrbashir** [comment]
Thanks for the contribution :heart:

**Comment by pashokitsme** [comment]
Oops, you're right. Fixed

**Comment by pashokitsme** [comment]
@amrbashir

**Review by amrbashir — DISMISSED** [review]

**Review by amrbashir — APPROVED** [review]
