### PR TITLE
fix(sql): add SQL support for Postgres `NUMERIC` and custom data types (fix: #3158)

### LINKED ISSUE #3158: [Plugin-SQL] unsupported datatype: NUMERIC
### Describe the bug

Unable to query data from DECIMAL-type columns in PostgreSQL.

### Reproduction

```sql
CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    price DECIMAL(10, 2) NOT NULL CHECK (price > 0),
);

INSERT INTO products (id, price) VALUES
('Laptop', 999.99),
('Mouse', 19.99)
```

```js
db.select(SELECT * FROM products)
```

### Expected behavior

Expected to correctly retrieve the data.

### Full `tauri info` output

```text
[⚠] Environment
    - OS: Mac OS 26.1.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ Xcode: 26.1.1
    ✔ rustc: 1.91.1 (ed61e7d7e 2025-11-07) (Homebrew)
    ✔ cargo: 1.91.1 (Homebrew)
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 25.2.1
    - npm: 11.6.2
    - bun: 1.3.4
    - deno: deno 2.5.6

[-] Packages
    - tauri 🦀: 2.9.5
    - tauri-build 🦀: 2.5.3
    - wry 🦀: 0.53.5
    - tao 🦀: 0.34.5
    - @tauri-apps/api  ⱼₛ: 2.9.1
    - @tauri-apps/cli  ⱼₛ: 2.9.6

[-] Plugins
    - tauri-plugin-sql 🦀: 2.3.1
    - @tauri-apps/plugin-sql  ⱼₛ: 2.3.1
    - tauri-plugin-opener 🦀: 2.5.2
    - @tauri-apps/plugin-opener  ⱼₛ: 2.5.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
unsupported datatype: NUMERIC
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mikenikles**
This PR adds support for Postgres `NUMERIC` (#3158) and custom data types. 

The following `invoice_type` can be used for testing:

```sql
CREATE TYPE invoice_type AS ENUM (
    'outgoing_invoice',
    'incoming_invoice',
    'credit_note',
    'debit_note',
    'proforma'
);

CREATE TABLE invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    type invoice_type NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL
);

INSERT INTO invoices (invoice_number, type, subtotal, issue_date, due_date)
VALUES
    ('INV-2026-001', 'outgoing_invoice', 4500.00, '2026-01-10', '2026-02-10'),
    ('INV-2026-002', 'incoming_invoice', 12750.00, '2026-02-01', '2026-03-01'),
    ('CN-2026-001', 'credit_note', 500.00, '2026-02-05', '2026-03-05');
```

### CODE REVIEW

File: plugins/sql/src/decode/postgres.rs [hunk 1]
```diff
@@ -107,8 +108,26 @@ pub(crate) fn to_json(v: PgValueRef) -> Result<JsonValue, Error> {
...
+            } else {
+                JsonValue::Null
+            }
+        }
         "VOID" => JsonValue::Null,
-        _ => return Err(Error::UnsupportedDatatype(v.type_info().name().to_string())),
+        // Handle custom types (enums, domains, etc.) by trying to decode as string
+        _ => {
+            if let Ok(v) = ValueRef::to_owned(&v).try_decode_unchecked::<String>() {
+                JsonValue::String(v)
```
Comment (FabianLars) [inline plugins/sql/src/decode/postgres.rs:128]: can we log something (with the log crate) here if this happens so we can keep track of missing types?

Comment (mikenikles) [reply plugins/sql/src/decode/postgres.rs:128]: Good idea, I added a log statement in be963c2.

**Review by FabianLars — APPROVED** [review]
