### PR TITLE
fix(updater): Escape current_exe args for nsis installer

### LINKED ISSUE #2752: [bug] Updating an app launched with arguments that have a space in them does not relaunch the app after update
On windows, if a tauri app is launched with arguments that have a space in them and an update is available, the updater will download and install the new version, but will fail to relaunch the app. Running `app.exe --with "Some Argument"` while an update is available will download, install and close the current instance of the app, but will not relaunch it.

### PR DESCRIPTION
**Pull request by FabianLars**
fixes #2752

I took a more conservative approach than i first wanted after reading Tony's comment. Really didn't want to touch the bundler or nsis utils at the moment and this whole cli arg stuff gives me a headache.
Maybe we can revise this whole logic when we refactor the code a bit (if that happens).

also i think we'll need to double check the msi escape method. looks like i missed args with spaces not starting with `-` ? Can't test it right now.

### CODE REVIEW

File: plugins/updater/src/updater.rs [hunk 1]
```diff
@@ -1363,6 +1371,21 @@ impl PathExt for PathBuf {
     }
 }
 
+#[cfg(windows)]
+fn escape_nsis_current_exe_arg(arg: &&OsStr) -> String {
+    let mut arg = dbg!(arg.to_string_lossy().to_string());
```
Comment (FabianLars) [inline plugins/updater/src/updater.rs]:
```suggestion
    let mut arg = arg.to_string_lossy().to_string();
```

File: plugins/updater/src/updater.rs [hunk 2]
```diff
@@ -1363,6 +1371,21 @@ impl PathExt for PathBuf {
...
 
+#[cfg(windows)]
+fn escape_nsis_current_exe_arg(arg: &&OsStr) -> String {
+    let mut arg = arg.to_string_lossy().to_string();
+
+    /* if arg.contains('"') {
+        arg = arg.replace('"', r#""""#);
+    } */
+
+    if arg.contains(' ') || arg.contains('\t') || arg.contains('/') {
```
Comment (Legend-Master) [inline plugins/updater/src/updater.rs]: Do we need to escape `/`? (by the way, just from testing, even if you add a surrounding quote at `/SOME_RANDOM_ARGS`, NSIS's `GetOptions` function seems to still treat that as the end of the previous option)

File: plugins/updater/src/updater.rs [hunk 3]
```diff
@@ -1363,6 +1371,21 @@ impl PathExt for PathBuf {
     }
 }
 
+#[cfg(windows)]
+fn escape_nsis_current_exe_arg(arg: &&OsStr) -> String {
```
Comment (amrbashir) [inline plugins/updater/src/updater.rs:1376]: we should add unit tests for this function as well

File: plugins/updater/src/updater.rs (hunk 2 above)
Comment (FabianLars) [reply plugins/updater/src/updater.rs]: Yes, I added this because without it `app.exe path/to --whatever` breaks on the /

Didn't think about args starting with a /

Comment (Legend-Master) [reply plugins/updater/src/updater.rs]: Looks like it, don't know how we escape `/` to be honest, but quotes don't seem to work for me

image

Comment (FabianLars) [reply plugins/updater/src/updater.rs]: Yeah me neither, no symbol worked so I went back to quotes. That definitely worked for me in the updater though, will double check when I'm back home, maybe I reverted too much.

File: plugins/updater/src/updater.rs (hunk 3 above)
Comment (FabianLars) [reply plugins/updater/src/updater.rs:1376]: Problem is I don't know what everything's actually supposed to look like (compared to MSI where i had a rough idea). This was all trial and error. So we can't really use them to confirm this PR but only to make sure it keeps its behavior over time.

Comment (FabianLars) [reply plugins/updater/src/updater.rs:1376]: But will do when I'm back

File: plugins/updater/src/updater.rs (hunk 2 above)
Comment (Legend-Master) [reply plugins/updater/src/updater.rs]: Hmm never mind, I think it works in `ShellExecuteW` 😂

image

When I execute it from the powershell, `DetailPrint "$CMDLINE"` gives me this which doesn't have the quotes in them

image

File: plugins/updater/src/updater.rs [hunk 4]
```diff
@@ -1363,6 +1371,21 @@ impl PathExt for PathBuf {
...
+
+    /* if arg.contains('"') {
+        arg = arg.replace('"', r#""""#);
+    } */
+
+    if arg.contains(' ') || arg.contains('\t') || arg.contains('/') {
+        arg = format!("\"{arg}\"");
+    }
+
+    arg
```
Comment (Legend-Master) [inline plugins/updater/src/updater.rs]:
```suggestion
    let arg = arg.to_string_lossy().to_string();
    if arg.contains(' ') || arg.contains('\t') || arg.contains('/') {
        format!("\"{arg}\"")
    } else {
        arg
    }
```

Comment (FabianLars) [reply plugins/updater/src/updater.rs]: That's a reminder. Couldn't test " in args yet (well I tried but rusts args parsing is weird (It's probably me))

Comment (Legend-Master) [reply plugins/updater/src/updater.rs]: I see, after some testing, I think only the one from the std really worked, basically, you need to escape `"` as `\"` (it also handles the `\"` case to `\\\"` I believe)

```suggestion
    let mut cmd: Vec<char> = Vec::new();

    let quote = arg.chars().any(|c| c == ' ' || c == '\t' || c == '/') || arg.is_empty();
    let escape = true;
    if quote {
        cmd.push('"');
    }

    let mut backslashes: usize = 0;
    for x in arg.chars() {
        if escape {
            if x == '\\' {
                backslashes += 1;
            } else {
                if x == '"' {
                    // Add n+1 backslashes to total 2n+1 before internal '"'.
                    cmd.extend((0..=backslashes).map(|_| '\\'));
                }
                backslashes = 0;
            }
        }
        cmd.push(x);
    }

    if quote {
        // Add n backslashes to total 2n before ending '"'.
        cmd.extend((0..backslashes).map(|_| '\\'));
        cmd.push('"');
    }
    cmd.into_iter().collect()
```

My mind is completely gone now after looking at them 😂, need some rests

Comment (FabianLars) [reply plugins/updater/src/updater.rs]: Have a good rest haha

My problem in testing was that I couldn't even get the " into the initial app instance's env::args() call lol
I think I messed up my Powershell profile _again_

Anyway, will get back to this tomorrow

Comment (Legend-Master) [reply plugins/updater/src/updater.rs]: try with `app.exe '"some args"'`, `'` escapes things inside in powershell

Comment (FabianLars) [reply plugins/updater/src/updater.rs]: Yeah that's what I tried first though can't remember if I typed something inbetween.

Comment (FabianLars) [reply plugins/updater/src/updater.rs]: okay either my powershell instance is broken beyond repair or that std args parser is missing a few edge cases (i may be testing stuff that aren't ever used idk). will just use this and call it a day.

File: plugins/updater/src/updater.rs [hunk 5]
```diff
@@ -1363,6 +1371,40 @@ impl PathExt for PathBuf {
     }
 }
 
+// adapted from https://github.com/rust-lang/rust/blob/1c047506f94cd2d05228eb992b0a6bbed1942349/library/std/src/sys/args/windows.rs#L174
+#[cfg(windows)]
+fn escape_nsis_current_exe_arg(arg: &&OsStr) -> String {
+    let arg = arg.to_string_lossy();
+    let mut cmd: Vec<char> = Vec::new();
+
+    let quote = arg.chars().any(|c| c == ' ' || c == '\t' || c == '/') || arg.is_empty();
```
Comment (Legend-Master) [inline plugins/updater/src/updater.rs:1381]: Let's add a comment here since `/` is not checked by rust standard library

File: plugins/updater/src/updater.rs [hunk 6]
```diff
@@ -1493,4 +1493,47 @@ mod tests {
...
+            "--empty=",
+            "--arg=value",
+            "\"some space\"",
+            "\"--arg value\"",
+            "\"--arg=unwrapped space\"",
+            "--arg=\\\"wrapped\\\"",
+            "\"--arg=\\\"wrapped space\\\"\"",
+            "\"--arg=midword\\\"wrapped space\\\"\"",
+            "\"\"",
+        ];
```
Comment (Legend-Master) [inline plugins/updater/src/updater.rs:1531]: Can we use `r#` here? I'm having a hard time reading through this 😂

Comment (FabianLars) [reply plugins/updater/src/updater.rs:1531]: Can't you just let me be lazy for once 😭 I copied the failed test results and they were in this format and I didn't want to read them either haha

Will do when I'm back home

Comment (Legend-Master) [reply plugins/updater/src/updater.rs:1531]: Actually, rust analyzer shows me the resolved the literal, cool, guess it's all good, the `r#` thing isn't that easy to read either when used with `"` anyways 😂 (e.g. `r#""""#`)

image

Comment (FabianLars) [reply plugins/updater/src/updater.rs:1531]: oh what, that's awesome. i never noticed that...

**Review by Legend-Master — APPROVED** [review]

**Review by amrbashir — APPROVED** [review]
