### PR TITLE
fix(updater): fallback to passive mode & fix `installerArgs` deserialzation

### LINKED ISSUE #1015: [updater] install mode is not passive by default if windows field is not declared
`Config::windows` is default to `None` instead of `Some(WindowsConfig::default())`

https://github.com/tauri-apps/plugins-workspace/blob/99bea2559c2c0648c2519c50a18cd124dacef57b/plugins/updater/src/config.rs#L84

https://github.com/tauri-apps/plugins-workspace/blob/99bea2559c2c0648c2519c50a18cd124dacef57b/plugins/updater/src/updater.rs#L557-L574

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #1015

Also fixes `installerArgs` not working in tauri config files

### CODE REVIEW

File: plugins/updater/src/config.rs [hunk 1]
```diff
@@ -113,3 +118,13 @@ impl<'de> Deserialize<'de> for UpdaterEndpoint {
...
+
+fn deserialize_os_string<'de, D>(deserializer: D) -> Result<Vec<OsString>, D::Error>
+where
+    D: Deserializer<'de>,
+{
+    Ok(Vec::<String>::deserialize(deserializer)?
+        .into_iter()
+        .map(OsString::from)
+        .collect::<Vec<_>>())
+}
```
Comment (amrbashir) [inline plugins/updater/src/config.rs]: This is effectively the same as deserializing a `String`, so let's just change `installer_args` field type to `Vec<String>` and remove the custom deserialization.

File: plugins/updater/src/config.rs [hunk 2]
```diff
@@ -81,7 +85,8 @@ pub struct Config {
     /// Signature public key.
     pub pubkey: String,
     /// The Windows configuration for the updater.
-    pub windows: Option<WindowsConfig>,
+    #[serde(default)]
+    pub windows: WindowsConfig,
```
Comment (amrbashir) [inline plugins/updater/src/config.rs]: I would rather keep this as `None` and just apply a default installation mode if it was `None`

**Review by amrbashir — CHANGES_REQUESTED** [review]

File: plugins/updater/src/config.rs (hunk 1 above)
Comment (Legend-Master) [reply plugins/updater/src/config.rs]: If we change this to `String`, do we want to also change the one from Builder to also be `String`?

File: plugins/updater/src/config.rs (hunk 2 above)
Comment (Legend-Master) [reply plugins/updater/src/config.rs]: Ok, I just thought this is cleaner for the consumers so that they can handle 1 less `Option`

File: plugins/updater/src/config.rs (hunk 1 above)
Comment (Legend-Master) [reply plugins/updater/src/config.rs]: Also, I would like to open another PR to migrate current powershell implementation to `ShellExecute` to avoid flushing powershell window, in that case I think `String` type makes more sense as we will convert it though `HSTRING::from` anyway

Comment (amrbashir) [reply plugins/updater/src/config.rs]: > If we change this to `String`, do we want to also change the one from Builder to also be `String`?

yeah let's do it



> Also, I would like to open another PR to migrate current powershell implementation to `ShellExecute` to avoid flushing powershell window, in that case I think `String` type makes more sense as we will convert it though `HSTRING::from` anyway

`HSTRING` can convert from `OsString` as well but that's beside the point, `ShellExecute` sounds good to me.

File: plugins/updater/src/config.rs (hunk 2 above)
Comment (amrbashir) [reply plugins/updater/src/config.rs]: I prefer to write `None` that `WindowsConfig::default` when using the `Config` struct from rust.

**Comment by Legend-Master** [comment]
Not sure why it can't pick up `installer_args` if `windows` field is `Option<WindowsConfig>`, `WindowsConfig` works though

**Comment by Legend-Master** [comment]
Strange, `cargo test --bin app-updater` on my machine succeed

**Comment by Legend-Master** [comment]
Found the problem, this part is still handled from tauri itself, not sure why changing `installer_args` to be not an `Option` fixes the problem

https://github.com/tauri-apps/tauri/blob/45384ab3aa44687f25323ebf367058270ec3a4d3/tooling/cli/src/interface/rust.rs#L780-L783

**Review by amrbashir — APPROVED** [review]
Sorry for the later reply, I have decided to revert back to `OsString` and go with your original solution, deserialize from string first.

Thanks for contribution
