### PR TITLE
fix(shell): run sidecar with dots in filename, closes #2310

### LINKED ISSUE #2310: [bug] Tauri does not support sidecar filenames with dots
### Describe the bug

When trying to use a sidecar with a filename that contains dots, Tauri will not handle it properly.

Additionally, if the sidecar's filename has a prefix that is the same as the name of the Tauri app, running `npm run tauri dev` will launch an endless number of app windows until you shut down the terminal or close the computer.

### Reproduction

For an app called CoolApp, which produces an executable like `CoolApp.exe`

Working: `"externalBin": ["binaries/bugrepro"]`

NOT WORKING: `"externalBin": ["binaries/bug.repro"]`
Throws error `Failed to spawn sidecar: Io(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })`

NOT WORKING: `"externalBin": ["binaries/CoolApp.Server"]`
Tauri launches the app endlessly until terminal closed or computer shut down

### Expected behavior

Filenames with dots supported.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 131.0.2903.112
    ✔ MSVC: 
        - Visual Studio Build Tools 2022
        - Visual Studio Enterprise 2022
    ✔ rustc: 1.84.0 (9fc6b4312 2025-01-07)
    ✔ cargo: 1.84.0 (66221abde 2024-11-19)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - pnpm: 9.12.3
    - npm: 10.2.3
    - deno: deno 2.1.5

[-] Packages
    - tauri 🦀: 2.2.0
    - tauri-build 🦀: 2.0.4
    - wry 🦀: 0.48.0
    - tao 🦀: 0.31.1
    - @tauri-apps/api : 2.2.0
    - @tauri-apps/cli : 2.2.3 (outdated, latest: 2.2.4)

[-] Plugins
    - tauri-plugin-opener 🦀: 2.2.3
    - @tauri-apps/plugin-opener : 2.2.3
    - tauri-plugin-websocket 🦀: 2.2.1
    - @tauri-apps/plugin-websocket : 2.2.1
    - tauri-plugin-shell 🦀: 2.2.0
    - @tauri-apps/plugin-shell : 2.2.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**

### CODE REVIEW

**Comment by FabianLars** [comment]
does this need to be changed too? https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/shell/src/commands.rs#L118

Also i think we have to check if it ends with `.exe` already before appending it i think i remember seeing people including it in the name (didn't try it myself but i think this would cause issues elsewhere so idk how valuable a check is, i just think it wouldn't hurt)

File: plugins/shell/src/commands.rs [hunk 1]
```diff
@@ -115,7 +115,12 @@ fn prepare_cmd<R: Runtime>(
     let mut command = if options.sidecar {
         let program = PathBuf::from(program);
         let program_as_string = program.display().to_string();
-        let program_no_ext_as_string = program.with_extension("").display().to_string();
+        let has_extension = program.extension().is_some_and(|ext| ext == "exe");
+        let program_no_ext_as_string = if has_extension {
+            program.with_extension("").display().to_string()
+        } else {
+            program_as_string.clone()
+        };
```
Comment (FabianLars) [inline plugins/shell/src/commands.rs:123]: i wish `trim_suffix` would be stabilized already, that would be so much nicer

**Review by FabianLars — APPROVED** [review]
