### PR TITLE
fix(shell): fix inlined docs for scope

### LINKED ISSUE #1648: [bug] shell api docs showcase plugins.shell config for scope instead of capabilities
### Describe the bug

It looks like `tauri.conf.json` does not accept the `plugins > shell > scope` setting, as indicated by the shell `Command` docs. This results in an error when trying to spawn any Command.

### Reproduction

Set up an app from scratch, enable the shell plugin, try to configure the scope as indicated in the docs at https://v2.tauri.app/reference/javascript/shell/#example-scope-configuration

```
{
  "plugins": {
    "shell": {
      "scope": [
        {
          "name": "run-git-commit",
          "cmd": "git",
          "args": ["commit", "-m", { "validator": "\\S+" }]
        }
      ]
    }
  }
}
```

### Expected behavior

_No response_

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.2.0
    - pnpm: 7.11.0
    - yarn: 1.22.19
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-rc.1
    - tauri-build [RUST]: 2.0.0-rc.1
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

```text
error while running tauri application: PluginInitialization("shell", "Error deserializing 'plugins.shell' within your Tauri configuration: unknown field `scope`, expected `open`")
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
closes #1648

### CODE REVIEW

File: plugins/shell/guest-js/index.ts [hunk 1]
```diff
@@ -35,20 +35,21 @@
  *
  * CLI: `git commit -m "the commit message"`
  *
- * Configuration:
+ * Capabilitiy:
```
Comment (lucasfernog) [inline plugins/shell/guest-js/index.ts]:
```suggestion
 * Capability:
```

**Review by lucasfernog — APPROVED** [review]
