### PR TITLE
fix(http): fix aborting a streaming response

### LINKED ISSUE #2557: HTTP: cancelling request not working for streaming
Once `fetch_read_body` is fired, aborting the fetch will stop working

https://github.com/tauri-apps/tauri-plugin-http/blob/918e02820d7963030993e902f808ccc7995bd509/guest-js/index.ts#L256

### PR DESCRIPTION
**Pull request by amrbashir**
closes #2557

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

File: plugins/http/src/commands.rs [hunk 1]
```diff
@@ -415,26 +415,42 @@ pub async fn fetch_send<R: Runtime>(
...
     };
 
-    let mut res = Arc::into_inner(res).unwrap().0;
+    // SAFETY: we can access the inner value mutably
+    // because we are the only ones with a reference to it
+    // and we don't want to use `Arc::into_inner` because we want to keep the value in the table
+    // for potential future calls to `fetch_cancel_body`
+    let res_ptr = Arc::as_ptr(&res) as *mut ReqwestResponse;
+    let res = unsafe { &mut *res_ptr };
+    let res = &mut res.0;
```
Comment (FabianLars) [inline plugins/http/src/commands.rs:430]: this still sounds pretty risky to me

**Review by FabianLars — APPROVED** [review]
I also only really tested this https://github.com/tauri-apps/plugins-workspace/issues/2557#issuecomment-2745134043

**Comment by BTMuli** [comment]
This PR breaks the original request mechanism, causing sent requests to never receive the response stream and hang indefinitely😢

Just test a simple fetch causes a breaking bug,plz revert this pr or fix it😢

**Comment by BTMuli** [comment]
It's my mistake,to adapt this pr,specify the frontend JS API is neeed:
```json
"@tauri-apps/plugin-http": "github:tauri-apps/tauri-plugin-http",
```
without above and simply set below will broken😢
```toml
[dependencies.tauri-plugin-http]
git = "ssh://git@github.com/tauri-apps/plugins-workspace.git"
branch = "v2"
```
